adv calculator
codecyclecommunity/learning-at-codecycle pull request #1122
Opened 2023-03-13 08:03 UTC by jaysurya-gounder

# Pull request

## Implement

- [x] Update pull request (title, assignee, labels, projects, implement, measure)
- [x] Update issue numbers here which will be fixed by this PR | Fixes #
- [x] Update labels for clarity & PR workflow
- [x] Add/Update comments in code
- [x] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [x] Add/Update change logs, docs and release notes

## Measure

- [x] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [x] Review change logs, docs & release notes
- [x] After completing all subtasks validate and make PR ready to merge

2023-03-17 04:48 UTC, beingminimal requested changes

2023-03-17 06:45 UTC, jaysurya-gounder commented on individual-projects/2023/jaysurya-gounder-190770116031/adv-calulator/index.html
> +    <script src="calculator.js"></script>
@beingminimal Sorry sir, i change the js file name now please review my task....

2023-03-22 03:20 UTC, beingminimal approved these changes

2023-03-22 03:46 UTC, jaysurya-gounder commented
@beingminimal Merging is blocked, How can i merge my branch to main repo??

2023-03-22 04:37 UTC, beingminimal approved these changes

2023-03-22 04:37 UTC, beingminimal commented
you need to mark comments as resolve to merge.

2023-03-22 04:48 UTC, merged