FlexBox
codecyclecommunity/learning-at-codecycle pull request #1197
Opened 2023-03-28 05:06 UTC by Prapti-Patel

# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

2023-03-28 05:06 UTC, Prapti-Patel commented
@beingminimal  Please Review

2023-03-28 06:56 UTC, beingminimal commented
@patel-rudra17 Review this PR

2023-03-28 11:09 UTC, patel-rudra17 commented
Before doing task please refer the proper guidance link  (https://flexboxfroggy.com/) .

2023-04-03 06:39 UTC, Prapti-Patel commented
@patel-rudra17 sir, I had completed all the task in this link (https://flexboxfroggy.com/). please review.

2023-04-03 09:14 UTC, patel-rudra17 requested changes

2023-04-03 09:14 UTC, patel-rudra17 commented on individual-projects/2023/Prapti-Patel-190770107179/FlexBox/index.html
> +        #pond {
where is the id in your body .....

here you have to use class = "icons"

2023-04-03 09:14 UTC, patel-rudra17 commented on individual-projects/2023/Prapti-Patel-190770107179/FlexBox/index.html
>  </html>
why you close html second time.

2023-04-03 09:24 UTC, Prapti-Patel commented
@patel-rudra17 I update it sir. Please review

2023-04-03 10:21 UTC, patel-rudra17 approved these changes

2023-04-03 10:26 UTC, merged