adv-function
codecyclecommunity/learning-at-codecycle pull request #1202
Opened 2023-03-28 07:31 UTC by jayesh-jagarwal

# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

2023-03-28 07:32 UTC, jayesh-jagarwal commented
@beingminimal please review

2023-04-03 05:21 UTC, jayesh-jagarwal commented
@beingminimal

2023-04-03 10:02 UTC, beingminimal requested changes
Please complete all the tasks given as per the issue and resubmit for review

2023-04-05 03:52 UTC, beingminimal approved these changes

2023-04-10 08:29 UTC, merged