accesibility 3
codecyclecommunity/learning-at-codecycle pull request #1203
Opened 2023-03-28 09:13 UTC by Himani-Patel12

# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

2023-03-28 10:25 UTC, beingminimal commented
@KunalChudasama Please review this

2023-03-28 11:11 UTC, KunalChudasama commented on individual-projects/2023/Himani-Patel-190770107153/Accesibility 3/index.html
> +        </article>
No need to use article tag here..and all links would be in the above section.

2023-03-28 11:13 UTC, KunalChudasama commented on individual-projects/2023/Himani-Patel-190770107153/Accesibility 3/index.html
> +            <img src="https://www.traveltechnologysolution.com/webroot/images/about_us.jpg" alt="graph">
this img would be the part of the above section.

2023-03-28 11:16 UTC, KunalChudasama requested changes
Changes Required

2023-03-29 08:58 UTC, Himani-Patel12 commented
@KunalChudasama I changed it. Please review.

2023-03-30 03:31 UTC, KunalChudasama approved these changes

2023-04-06 08:03 UTC, merged