learn Positioning in CSS
codecyclecommunity/learning-at-codecycle pull request #1240
Opened 2023-04-03 07:22 UTC by NeelRavalt

# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

2023-04-03 11:29 UTC, Amoli-Patel requested changes

2023-04-03 17:45 UTC, NeelRavalt commented
@Amoli-Patel changes done please review

2023-04-04 03:38 UTC, Amoli-Patel approved these changes

2023-04-04 06:49 UTC, NeelRavalt commented on individual-projects/2023/neel-raval-191210116061/css-positioning/index.html
> +        <div class="C"><img src="https://clipartcraft.com/images/teddy-bear-clipart-birthday.png" width="100px" height="100px" alt="logo"></div>
changes done

2023-04-04 11:48 UTC, merged