Flex_01
codecyclecommunity/learning-at-codecycle pull request #1242
Opened 2023-04-03 10:23 UTC by Prapti-Patel

# Pull request

## Implement

- [ ] Update pull request (title, assignee, labels, projects, implement, measure)
- [ ] Update issue numbers here which will be fixed by this PR | Fixes #
- [ ] Update labels for clarity & PR workflow
- [ ] Add/Update comments in code
- [ ] Self code review as per this [guide](https://google.github.io/eng-practices/review/)
- [ ] Add/Update change logs, docs and release notes

## Measure

- [ ] What: Pull Request Title | Why: PR Detail | How: DIM | When: Timeline | Who: Assignee & Reviewer
- [ ] Review change logs, docs & release notes
- [ ] After completing all subtasks validate and make PR ready to merge

2023-04-03 10:24 UTC, Prapti-Patel commented
@beingminimal Please review.

2023-04-04 03:44 UTC, KunalChudasama commented on individual-projects/2023/Prapti-Patel-190770107179/Flex_01/style.css
> +    position: absolute;
Why you have used position....?

2023-04-04 03:46 UTC, KunalChudasama commented on individual-projects/2023/Prapti-Patel-190770107179/Flex_01/style.css
> +    display: inline;
why you have used display inline here...??

2023-04-04 03:50 UTC, KunalChudasama commented on individual-projects/2023/Prapti-Patel-190770107179/Flex_01/style.css
> +    align-items: flex-end;
what is the need of Align-items:flex-end...?

2023-04-04 03:51 UTC, KunalChudasama requested changes
Changes Required

2023-04-04 03:56 UTC, KunalChudasama commented
@Prapti-Patel How many examples of flexbox you have completed..?

2023-04-04 08:56 UTC, Prapti-Patel commented
@KunalChudasama I have completed two examples of flexbox

2023-04-04 11:20 UTC, KunalChudasama commented
@Prapti-Patel what is the file name of the second example.....???

2023-04-04 12:34 UTC, Prapti-Patel commented
@KunalChudasama Flex_02 
But this example approved by Amoli ma'am

2023-04-05 03:49 UTC, KunalChudasama approved these changes

2023-04-05 04:38 UTC, merged